version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_PORT=5432
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - DATABASE_DBNAME=postgres
  #     - DATABASE_SSLMODE=disable
  #     - SERVER_PORT=8080
  #     - SERVER_READTIMEOUT=15
  #     - SERVER_WRITETIMEOUT=15
  #     - SERVER_IDLETIMEOUT=60
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 